package com.property.manage.dao.mapper;

import com.github.pagehelper.Page;
import com.property.manage.annotation.MyBatisDao;
import com.property.manage.dao.common.BaseMapper;
import com.property.manage.dao.model.User;

import java.util.List;

@MyBatisDao
public interface UserMapper extends BaseMapper<User> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Override
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @Override
    List<User> selectAll();

    User getById(Integer id);

    /**
     * 分页查询
     * @return
     */
    Page<User> getUserByPage();
}