# SERVER
server:
  tomcat:
    uri-encoding: UTF-8
    max-connections: 500
    min-spare-threads: 25
    max-threads: 300
    accept-count: 200
  port: 8080

#开发配置
spring:
  application:
    name: propertyManage
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 901105
    druid:
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      minIdle: 5
      validationQuery: SELECT 1 FROM DUAL
      useGlobalDataSourceStat: true
      maxWait: 60000
      filters: stat,wall,slf4j
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      testWhileIdle: true
      testOnBorrow: false
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
      testOnReturn: false
      initial-size: 5
      driver-class-name: com.mysql.cj.jdbc.Driver
      maxActive: 20
  freemarker:
    template-loader-path: classpath:/
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

# MYBATIS
mybatis:
  type-aliases-package: com.property.manage.dao.mapper
  mapper-locations: classpath:mapper/**/**.xml

# PAGEHELPER
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

# LOG
logging:
  config: classpath:log4j-dev.xml




